WITH Available_Cars AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE,
           DP.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
           ON C.CAR_ID = RH.CAR_ID
           AND (RH.END_DATE >= '2022-11-01' AND RH.START_DATE <= '2022-11-30')
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
           ON C.CAR_TYPE = DP.CAR_TYPE
           AND DP.DURATION_TYPE = '30일 이상'
    WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
          AND RH.CAR_ID IS NULL
),
Rental_Fee AS (
    SELECT CAR_ID, CAR_TYPE,
           DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100.0) AS FEE
    FROM Available_Cars
)
SELECT CAR_ID, CAR_TYPE, ROUND(FEE,0)
FROM Rental_Fee
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
